global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "ollama-backend"
    static_configs:
      - targets: [ "ollama-backend:8080" ]
    metrics_path: /metrics
  - job_name: "prometheus"
    static_configs:
      - targets: [ "prometheus:9090" ]
